ERROR    root:custom_decorators.py:33 An unexpected error occurred during 'test_get_delay_endpoint': Invalid URL 'None/delay/3': No scheme supplied. Perhaps you meant https://None/delay/3?